### ISSUE TITLE
Status box is truncated

### ISSUE THREAD

**Issue by marco-piazzi** [onlyutkarsh/VSTSStatusMonitorChrome#1]
Version: 0.0.1
![2017-09-18 10_28_56-new issue onlyutkarsh_vstsstatusmonitorchrome](https://user-images.githubusercontent.com/12832793/30533943-3a201aa4-9c5c-11e7-878b-7e93f1147c49.png)

**Comment by onlyutkarsh** [comment]
Hey, @marcopiazzi, thanks for reporting this issue. I increased the height of popup in the latest version. Should be okay now. Please reopen if you still see the issue.
